### ISSUE TITLE
Support for ImageMagick 7.x

### ISSUE THREAD

**Issue by louiscloutierdakis** [gographics/imagick#101]
Currently, the master for imagick support ImageMagick <  7.x.
The last ImageMagick version is ImageMagick-7.0.3-4.
Is supporting ImageMagick 7.x in your plan?

**Comment by justinfx** [comment]
It would be nice if there were a v3 tag that covers ImageMagick 7.x

I can't say there is any formal plan though. It's more just, someone has to find time to do it. Alot of my own contributions to maintaining the library thus far have stemmed out if my own personal need to use it. Thus, because I don't have a need for ImageMagick 7.x support yet, it isn't something I have started. If I find spare time, I may work on it. Not sure when though.

Patches welcome from anyone immediately needing 7.x support!

**Comment by justinfx** [comment]
Relates to #95, #98 

I've pushed up WIP support for ImageMagick 7.x that is passing the few tests that we have. This was built against 7.0.3-4. There are still TODOs in the source that need to be looked at.

**Comment by justinfx** [comment]
[ImageMagick 7.x branch](https://github.com/gographics/imagick/tree/im-7)

**Comment by justinfx** [comment]
I've cleaned up, ported, and merged the `KernelInfo` work from @Danack (#89): a0a98fa0
Updated a few of the broken examples (still more though): 976561fc
And also fixed a little more memory management.

Hopefully someone else can comment on the state of this branch.

**Comment by justinfx** [comment]
To make it easier to test, I have tagged and pre-released ImageMagick 7.x support as Imagick v3:
https://github.com/gographics/imagick/releases/tag/v3.0.0

```go
import gopkg.in/gographics/imagick.v3/imagick
```

**Comment by justinfx** [comment]
3.0.0 released

**Comment by pkieltyka** [comment]
@justinfx well done! are you going to release gopkg.in/gographics/imagick.v3 ? or does that not make sense (btw: I haven't been following commits that closely)

**Comment by justinfx** [comment]
@pkieltyka , you should be good to go already. I had tagged v3.0.0 a little while back and had only marked it as a pre-release in github. I waited for some feedback but didn't hear anything, so I just figured I would make forward progress and clear the pre-release and close the ticket :-)

Let me know if you find issues. I am sure there are missing ImageMagick 7.0 features though, since my goal was just to get a working build that people can use.

**Comment by justinfx** [comment]
```
import gopkg.in/gographics/imagick.v3/imagick
```

**Comment by pkieltyka** [comment]
awesome! dont forget to update the README if you haven't already. thanks for the work!

**Comment by justinfx** [comment]
Yep, README had already been updated:
https://github.com/gographics/imagick/commit/c22a9fb8151818f12f3df2a576f5f27f0f10da75

Thanks!
