### ISSUE TITLE
Windows: examples\resize resize.exe error?

### ISSUE THREAD

**Issue by barcelona-messi** [gographics/imagick#102]
panic: ERROR_MISSING_DELEGATE: NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadIma
ge/501

goroutine 1 [running]:
panic(0x4a2180, 0xc0420443e0)
        C:/Go64/src/runtime/panic.go:500 +0x1af
main.main()
        C:/goget/src/gopkg.in/gographics/imagick.v2/examples/resize/main.go:20 +0x226

**Comment by justinfx** [comment]
Related to #87? 
That would be a problem building ImageMagick on windows, and it missing the decoder plugin for png. You can run the convert command to list the available formats and see if png is listed.

**Comment by barcelona-messi** [comment]
i want use ImageMagick while run resize.exe not install other things, is there a way?

**Comment by justinfx** [comment]
What I am trying to explain though, is that your resize.exe is built with the Imagick library, which is bindings on top of your ImageMagick. But if your ImageMagick is missing plugins to support formats, then you will see this error. I wanted you to check that your ImageMagick is built correctly. 

There are previous issues on this project where Windows users had a similar problem. Turned out they needed better build instructions for ImageMagick on windows

**Comment by justinfx** [comment]
Closing this issue, as it looks to me to be a problem with the install of ImageMagick and lacking the plugin support for certain image formats.
