### ISSUE TITLE
How to recover the fatal error form ImageMagick?

### ISSUE THREAD

**Issue by skyleelove** [gographics/imagick#121]
Hi,
     When I use gographics/imagick to process image,I got an error "unable to extent pixel cache `Success' @ fatal/cache.c/CacheSignalHandler/3625" from ImageMagick.Could I recover this error
to avoid my goroutine crash。How can I do to solve this problem.Thank you very much.

**Comment by justinfx** [comment]
Take a look at these following related links:

* http://www.imagemagick.org/script/architecture.php#tera-pixel
* https://github.com/danielquinn/paperless/issues/98

It looks to be related to converting large images and not having enough tmp scratch space. So ImageMagick doesn't have enough available memory to process your request. It doesn't look like there is anything you can do to catch this because ImageMagick literally terminates:

https://github.com/ImageMagick/ImageMagick/blob/f6ff9eaa865134189fce2cf73b109da589178bde/MagickCore/exception-private.h#L36

**Comment by skyleelove** [comment]
Hi,
   Thanks for answer.And then I want to know CGO to call CAPI。How about the performance?

**Comment by justinfx** [comment]
Is this an unrelated question? You want to know performance metrics on Go calling the C ImageMagick API via cgo?

**Comment by skyleelove** [comment]
Hi，
   This is other topic I want to ask.Could you give me some suggestion。 I want to know performance metrics on Go calling the C ImageMagick API via cgo。Because I use ResizeImage（）and CropImage（）spend a little more time.I do not know the reason.

                err := dest.ResizeImage(uint(new_width), uint(Height), imagick.FILTER_LANCZOS, 1)
		if err != nil {
			return err
		}
		dest.CropImage(uint(Width), uint(Height), int((new_width-Width)/2), 0)

**Comment by justinfx** [comment]
It has been quoted on the golang-nuts forum that the average overhead of calling into a C function from Go can be 10x of a normal Go function call. And with Go 1.8 they reduced the overhead by half. 

Now, your examples are not a tight loop. They are effectively 2 calls into C which is a very small number of calls. CGO is expensive when you are making frequent calls in loops or tons and tons of concurrent calls. It requires an OS thread to service the cgo call.

**Comment by skyleelove** [comment]
Thank you very much!
