### ISSUE TITLE
No Density Option

### ISSUE THREAD

**Issue by TheDeadCode** [gographics/imagick#122]
I want to convert a PDF to a PNG (300 DPI). Although the golang lib doesn't have the option to do that. I cannot export the pdf to a png with good enough resolution.

An example of another library:
http://magick.codeplex.com/SourceControl/latest#Samples/Magick.NET.Samples/Samples/Magick.NET/ConvertPDF.cs (ConvertPDFTOneImage | settings.Density)

Did you implement it and I didn't see it, or is it planned?

**Comment by justinfx** [comment]
Hi, 

You are referencing the Magick.net library for C#. It would be better to base your info off the ImageMagick C API ad that is what this Go library is wrapping. The .NET library might have introduced their own high level concepts, because I don't see MagickReadSettings or Density in the C Api.

Have you tried setting the resolution on your MagickWand before reading the pdf?

https://godoc.org/gopkg.in/gographics/imagick.v3/imagick#MagickWand.SetResolution

Let me know if that works. I am not sure what options might be available to be passed to the Ghostscript delegate. Maybe Density in the NET library gets translated into an option under the hood.

**Comment by TheDeadCode** [comment]
Hi there! I did try it and it did not work, sadly. I've been trying all day long, but couldn't find a solution. Do you have anything in mind?

**Comment by justinfx** [comment]
Can you be more specific about what you tried that did not work? Do you have a sample of your code?
When I tried a quick test, it seems to be producing a higher sampled result when I use `mw.SetResolution(300,300)` BEFORE I read the pdf:

```go
mw := imagick.NewMagickWand()
mw.SetResolution(300, 300)
mw.ReadImage(`/path/to/my.pdf`)
mw.WriteImage(`/path/to/out.png`)
```

**Comment by TheDeadCode** [comment]
Seems that was my error. I was using `SetImageResolution`. 

Sorry to disturb you!

**Comment by justinfx** [comment]
No worries. Good to see you have it working now.

**Comment by matiasAguilo** [comment]
justinfx, thanks for your help!!!
