### ISSUE TITLE
Catching TimeLimitExceeded Exception

### ISSUE THREAD

**Issue by fvm** [gographics/imagick#124]
Hi,

We're using the imagick package as part of a web-service. In our http server setup, we've imposed a read-timeout and write-timout of 120 seconds each, after which the connection gets dropped. ImageMagick itself also has a time-limit which we've set to 3600 seconds through the `policy.xml` file.

What we're seeing is that when this limit is exceeded, ImageMagick throws an Exception which takes down the whole application (line number depends on the ImageMagick version):

```
main: time limit exceeded `Operation canceled' @ fatal/cache.c/GetImagePixelCache/1798.
exit status 1
```

I've gone through the imagick code and at first glance there does seem to be some things in place which suggest this could be taken care of, meaning that instead of exiting, an error (specifically a `FATAL_ERROR_RESOURCE_LIMIT` error) is returned which can be dealt with.

Now for the questions... Is the current behaviour of exiting instead of returning an error intentional? And, is there a way of catching this exception and handling it without exiting?

Cheers,
Frank

**Comment by rogierlommers** [comment]
Please download [this](https://www.dropbox.com/s/d4oet9715kaxpc2/catching-timeouts-form-imagemagick.zip?dl=1) for an example of our problem and see screencast below. As you can see, we have a longrunning imagemagick process (which takes 3 seconds). When we set `mw.SetResourceLimit(imagick.RESOURCE_TIME, 10)`, no imagemagick timeout occurs, but when we set value to `1 second`, imagemagick timesout, but this is not correctly handled by gographics.

![kapture 2017-03-10 at 9 27 13](https://cloud.githubusercontent.com/assets/3907131/23788099/617cbc98-0575-11e7-853e-9cc5587bb894.gif)

**Comment by justinfx** [comment]
Rogier, thanks for the example of how to set a timeout value to deal with
this situation. That seems like a workable solution, given you allocate the
timeout value enough padding.

I agree that imagick should handle the exception since there isn't an easy
way for a consumer of the Go library to catch and handle it on their own.
I'm not familiar with the timeout exception but I suppose it needs to be
handled around any read or write operation on a file? I can't guarantee
when it will get looked at by myself or another maintainer, but we are
happy to accept a patch. Ideally it would convey an error message instead
of throwing a C exception.

Justin

**Comment by justinfx** [comment]
Just wanted to comment on this since I didn't end up getting time to look into it. 

It does seem that there is zero way to prevent this exiting behavior through the resource limits, as it is not implemented as an actual exception. C doesn't have exceptions anyways so it conforms to a C convention (kind of).

https://github.com/ImageMagick/ImageMagick/blob/f19d414d0ac4527544fef324969aa2a5d38b1027/MagickWand/magick-wand-private.h#L35

```c
#define ThrowWandFatalException(severity,tag,context) \
{ \
  ExceptionInfo \
    *fatal_exception; \
 \
  fatal_exception=AcquireExceptionInfo(); \
  (void) ThrowMagickException(fatal_exception,GetMagickModule(),severity,tag, \
    "`%s'",context); \
  CatchException(fatal_exception); \
  (void) DestroyExceptionInfo(fatal_exception); \
  MagickWandTerminus(); \
  _exit((int) (severity-FatalErrorException)+1); \
} 
```

You can see that this basically logs the warning, terminates ImageMagick and **kills your process**. This is pretty terrible and useless unless you are using limits only for a utility command that is meant to do a task and terminate. Its terrible for any long-lived process and should be avoided. There doesn't seem to be anything a bindings library could do at that layer. The act of terminating your process happens within the call into the C API and no exceptions are thrown (its C, not C++ anyways)
