### ISSUE TITLE
Build statically linked executable

### ISSUE THREAD

**Issue by apoorvam** [gographics/imagick#128]
I have a service using `gographics/imagick`, but to run this executable I have to install [ImageMagick](https://github.com/ImageMagick/ImageMagick) explicitly. How can I generate a statically linked executable of my app? I see that we can set `ldflags` and do this, Can someone give more details on this?

**Comment by justinfx** [comment]
Hi. Have you looked at #110? It contains information about static linking against ImageMagick and the various delegate libraries

**Comment by apoorvam** [comment]
Hello @justinfx Ya I did have a look at that issue and Im not sure of what references should be added as part of ldflags and cflags. I tried installing as below command in fresh Ubuntu box: 
`go install -tags no_pkgconfig -v gopkg.in/gographics/imagick.v3/imagick` 

But it fails saying `MagickWand/MagickWand.h` file is not found. I think I'll still have to install Imagemagick library first and then reference it in cgo_flags. I was thinking I will be able to build this without having to install ImageMagick C lib. Can you provide more details on what flags should be used?

**Comment by justinfx** [comment]
Using the `-tags no_pkgconfig` only tells the build to not try to call your pkg-config tool to ask it for the compiler and linker flags. That means you have to specify them manually in the form of static linking instead of dynamic. The information from the other ticket is the very first part where you set two environment variables to tell the Go tool your flags :

```
CGO_LDFLAGS=-lstdc++ -lXext -lX11 -Wl,-Bstatic     -lMagickWand-6.Q16 -lMagickCore-6.Q16      -lIlmImf -lImath -lHalf -lIlmThread -lIex    -ltiff     -ljpeg      -lfontconfig -lfreetype -lxml2 -lexpat -lpng12 -lbz2 -lfftw3 -lz -lm -Wl,-Bdynamic
CGO_CFLAGS=-fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6
```
If you look at those paths you will see the information is specific to where your includes and libraries live on your system, and also every specific delegate plugin you want to support. 

I think you have a misunderstanding of what static linking is. It would be impossible to compile and statically link the Go Imagick bindings into a program without having ImageMagick installed and built with static libraries available. Static linking means that the available static ImageMagick libraries will be packaged directly into the Imagick program so that they don't have to be dynamically found later on the system. 

So your first step would be to make sure you have static ImageMagick libraries. Then make sure you have static libraries for all the dependencies. It's a bit complicated but possible. I used to static link a program as well once I had all of this available at compile time.

**Comment by apoorvam** [comment]
@justinfx Thanks for the information, I now have a better understanding of it. That really helped!  I could generate the statically linked binary of Go Imagick by figuring out flags. `ldd imagick` gives `not a dynamic executable`. How can I verify it's built correct? 

All my other dependencies are pure-go ones. Slightly off topic... , Is there way I can tell `go build` to build all other dependencies of my app as usual and use Go Imagick thats already built?

**Comment by justinfx** [comment]
> How can I verify it's built correct?

Build a small program using statically linked Imagick and see if it works. Such as building any of the included example programs. Or, simply run the unit tests with "go test" + all of your static link flags. 

> Is there way I can tell go build to build all other dependencies of my app as usual and use Go Imagick thats already built?

"go build" is going to build all the dependencies in a temp area, then build your program, and then throw away the intermediate build stuff. What you probably want is to "go install" imagick, statically linked. That way when you "go build" your program it won't have to build Imagick again. I *think* that works if I remember right. 

But even aside from that, building your whole program, including imagick statically linked, should work from scratch
