### ISSUE TITLE
MSYS2 Installation

### ISSUE THREAD

**Issue by kcsampson** [gographics/imagick#141]
I ran through the msys2 installation instructions, however, it seems the latest mingw64 Image Magick package does not have any working delegates for postscript, jpeg, png etc.
I compiled sample resize.go successfully but gives the error: 
panic: ERROR_MISSING_DELEGATE: NoDecodeDelegateForThisImageFormat `JPEG' @ error/constitute.c/ReadImage/509

I don't see how msys2 pacman configures ImageMagick to have all the delegates.

**Comment by tfwio** [comment]
I've run into the same\
try manually installing an earlier msys2-imagemagick package.

[everything I'm doing here is under msys-bash terminal]

> [TMI:] It seems as though there's nothing wrong with the binary aspect of the imagemagick but I think perhaps there may be something mis-configured in respect to how the modules link to the configuration (AFAIK, in IM-v7x distros)—is not msys2 package-mgmt(s) fault.  If someone were to come up with a patch/fix, I'm sure the msys2-packager(s) might find this useful, otherwise from what I recall, msys2-package-mgmt suggests using graphicsmagick.

for my case under msys2: so far I've not run into any issues...

downloaded with wget
```
wget https://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/mingw-w64-x86_64-imagemagick-6.9.3.7-1-any.pk
g.tar.xz/download -o mingw-w64-x86_64-imagemagick-6.9.3.7-1-any.pkg.tar.xz
```
installed with pacman
```
pacman -U mingw-w64-x86_64-imagemagick-6.9.3.7-1-any.pkg.tar.xz
```
The rest was simple enough to figure out ;)\
[this is a one-liner, running from `${GOPATH}/src/gopkg.in/gographics/imagick.v2`]

```
MAGICK_CODER_MODULE_PATH=/mingw64/lib/ImageMagick-6.9.3/modules-Q16HDRI/coders go build ./imagick
```

Some of the demos expect or rely on X11 terminal (mac, *nix) so you can expect some simple errors with some of the demos — that said, I've run a few examples and they seem to be working fine.

----

### [ more TMI if helpful... ;]

Am using msys2-bash/terminal to build where of course I've got my go-environment configured (GOPATH, GOROOT, PATH=${PATH}:${GOROOT}/bin:${GOPATH}/bin, etc...) by way of some script that sets the following (only if needed)
```
GOROOT=/e/dev/tool/go-amd64
GOPATH=/c/Users/$USERNAME/Go
PATH=${PATH}:$GOROOT/bin:${GOPATH}/bin"
```
Also, am using Visual Studio Code configured to use msys2-bash in the integrated terminal.\
so if it helps, this is in my `<vscode-project-root>/.vscode/settings.json`...
```js
// ...
  "go.goroot": "[you-know]\\Go-amd64",
  "go.toolsEnvVars": {
    "PATH": "%PATH%;c:\\msys64\\usr\\bin;c:\\msys64\\mingw64\\bin",
    "LDFLAGS": "c:\\msys64\\mingw64\\lib;C:\\msys64\\mingw64\\x86_64-w64-mingw32\\lib"
     // TODO: help it find msys2 pkg-conf stuffs [hadn't tested this]
     //"PKG_CONFIG_PATH"="c:\\msys64\\mingw64\\lib\\pkgconfig"
  },
  "terminal.integrated.setLocaleVariables": true,
  "terminal.integrated.shell.windows":"C:\\msys64\\msys2_shell.cmd",
  "terminal.integrated.shellArgs.windows": [ "-mingw64", "-no-start", "-defterm" ],
  "terminal.integrated.cwd": "C:\\msys64\\usr\\bin",
// ...
```
I've noticed that it (vscode) complains about a integrated `'C'` project like this since the script-environment in vscode doesn't seem to see into the msys environment and the files its looking for (such as the pkg-conf files used in the build process).  not to mention (the obvious) weeding out redist files *could* be quite painful—can't say I'll attempt that any time soon).
