### ISSUE TITLE
BlurImage inflating PDF -> PNG conversion size.

### ISSUE THREAD

**Issue by crunk1** [gographics/imagick#148]
Admittedly, I'm an imagemagick novice, so be patient with me...

I'm trying to clean up and covert some PDFs of faxed text, so I figured a light blur would help. However, when I uncomment the blur line in the code below, image size blows up. For example, I have an image whose converted PNG size blows up from 53k to 1.5MB
```
func convertDoc(name string, pdf []byte) (string, error) {
	mw := imagick.NewMagickWand()
	defer mw.Destroy()
	mw.SetImageUnits(imagick.RESOLUTION_PIXELS_PER_INCH)
	mw.SetResolution(400, 400)
	if err := mw.ReadImageBlob(pdf); err != nil {
		return "", err
	}
	mw.SetFirstIterator()
	page := 0
	pngs := [][]byte{}
	for more := true; more; more = mw.NextImage() {
		i := mw.GetImage()
		i.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_REMOVE)
		i.SetColorspace(imagick.COLORSPACE_GRAY)
		//i.BlurImage(3, 1)
		i.SetImageCompressionQuality(100)
		i.SetFormat("png")
		path := fmt.Sprintf("out/%s-%d.png", name, page)
		i.WriteImage(path)
		pngs = append(pngs, i.GetImageBlob())
		page++
	}
	...
}
```

**Comment by justinfx** [comment]
I'm also not an expert in all-thing-imagemagick. If its not an issue specific to the bindings, you may find more support asking the ImageMagick forum? Off hand I am not sure why applying a blur operation would cause such a massive difference to the output file size. I would expect some kind of different because it would impact the effectiveness of the compression.  You are using a huge PPI (400), so maybe its because the original text is basically 2-tone which can compress well, and the blur really cancels that out?

**Comment by crunk1** [comment]
Yeah, 400 DPI is big, I get that. I figured it wouldn't be so bad with grayscale. Your more-than-2-tone theory could be correct. I'll have to play around with it more.

**Comment by justinfx** [comment]
@crunk1  is there anything else that can be done support-wise on this ticket?

**Comment by crunk1** [comment]
No, I think we're fine here.
