### ISSUE TITLE
package api design (Golang pattern)

### ISSUE THREAD

**Issue by avelino** [gographics/imagick#158]
Thinking of a pattern of go packages we use at the root of the repository all packages, today this package puts inside a paws called  `imagick`, thus generating a strange pattern for those who use, see below

today:

```go
import "gopkg.in/gographics/imagick.v2/imagick"
```

proposal:

```go
import "gopkg.in/gographics/imagick.v2"
```

example:

```go
package main

import "gopkg.in/gographics/imagick.v2"

func main() {
    imagick.Initialize()
    defer imagick.Terminate()

    mw := imagick.NewMagickWand()

    ...
}
```

The purpose of this issue is to better the package API and not criticize the work (which is very good), I'm willing to make this migration if the maintainers accepted (we can generate a version 3 to not break the compatibility of those using version 2)

**Comment by justinfx** [comment]
I agree that it would look nicer to not have the stuttering imagick name at the end. It was even worse before we were using gopkg.in, when it was imagick/imagick

Changing it at this point would mean it would need to be a new version, which would confuse people that are tracking say, patch versions in their vendor dependencies and would not get more updates unless they were aware of the change to the project. 

Also, we already have a v3 (see readme) to map to the complicated support we are providing for multiple ImageMagick api versions. V3 maps to ImageMagick 7. So in order to make the change you propose, we would have to do something like a v4 and v5 (dropping support for <= im-6.8.9-10)

I feel like at this point in time it may not be worth the trouble. Maybe this might make more sense when we discontinue support for ImageMagick 6 entirely? Then we can just create a v4 and be done with all these version streams.

**Comment by avelino** [comment]
I agree that it is complicated to break the package API, but I see it as an important change, it may not be important right now.

This issue is to plan this change, recommend reading[1]

[1] https://rakyll.org/style-packages/#clean-import-paths (pt-BR: http://www.avelino.xxx/guia-de-estilo-para-pacotes-go/)

**Comment by justinfx** [comment]
Can you explain why you feel it is important? The link you provided is a style guide aimed at best practices for structuring projects. But what you refer to as important, I see as just being a shorter import path. Furthermore, in the particular case of this project, the path would shorten to a base component that doesn't match the package name (imagick becomes imagick.v2). But maybe in the case of gopkg.in, this is the accepted convention anyways. 

Also, in the case of polyglot projects that provide multiple libraries and packages, one may end up seeing import paths like this: "github.com/gographics/imagick/go[/imagick?]"

If you also look at the new [vgo documentation](https://research.swtch.com/vgo-intro), Russ Cox suggests that the Go community will start seeing repository structure exposed in the form of major versions: "github.com/gographics/imagick/go[/imagick?]/v2"

So I really just need to understand why this change to an existing project is important, as opposed to just cleaner?

**Comment by justinfx** [comment]
Going to close this since there hasn't been any further clarifications about the motivation and value of the change, and I don't see any immediate plans to change the import paths. If there is enough feedback then we can reopen. Thanks!
