### ISSUE TITLE
Errors while using a `MagickWand` as a struct field

### ISSUE THREAD

**Issue by loehnertz** [gographics/imagick#160]
I am still quite new to Go!
I got one quick question though. I am not sure if I overlooked something but I could not get it to work to save an `*imagick.MagickWand` or an `imagick.MagickWand` as a field into a struct like so:

```go
type Image struct {
	Name       string
	Path       string
	Resolution struct {
		X int
		Y int
	}
	MagickWand *imagick.MagickWand
}
```

The saving into an instance of this struct still works fine but whenever I try to execute a method of the `MagickWand` I either get an `invalid memory address or nil pointer dereference` error when using a pointer to the `MagickWand`, it seems that it cannot really dereference the pointer as it always results in `nil`.

In contrast, if I use a direct value instead of a pointer inside of my struct, I always get this error: 
`Assertion failed: (wand != (MagickWand *) NULL), function MagickAdaptiveResizeImage, file wand/magick-image.c, line 254.`

However using the `MagickWand` directly as a variable works fine, so `ImageMagick` is functioning. 

Does anyone got a solution for me or is this behaviour expected due to the nature of the library?

**Comment by justinfx** [comment]
You should expect to use a pointer (`*imagick.MagickWand`) and not dereference it explicitely. The Go pointer to the struct is meant to keep the underlying C pointer alive until garbage collection. 

Do you have an example of how your are creating your `Image`? It just sounds like you aren't initializing your `MagickWand` field properly and leaving it as a nil pointer. I'm going to take a wild guess that it has something to do with a method you have that is using a value receiving instead of a pointer receiver:

```go
// Don't do this
func (i Image) Init() {
    i.MagickWand = ...
}

// Use a pointer receiver
func (i *Image) Init() {
    i.MagickWand = ...
}
```

**Comment by loehnertz** [comment]
Thanks for your fast answer! :) 
But I am indeed initializing it via a pointer receiver:
```go
// AttachMagickWandInstance creates a MagickWand instance, loads the image and attaches the instance to the `Image` structure.
func (image *Image) AttachMagickWandInstance() {
	mw := imagick.NewMagickWand()
	if err := mw.ReadImage(image.Path + image.Name); err != nil {
		log.Fatal(err)
	} else {
		image.MagickWand = mw
	}
}
```

And in another package I am calling this method. Later I try to resize the image:
```go
image.AttachMagickWandInstance()

if err := image.MagickWand.AdaptiveResizeImage(1000, 1000); err != nil {
	log.Fatalf("An error occured while resizing an image (%v): %v", image, err)
}
```
The call to `AdaptiveResizeImage()` then yields the error `invalid memory address or nil pointer dereference` and crashes the application.

Do you have any further idea what the problem could be?

**Comment by justinfx** [comment]
Can you show the actual stack trace for the crash? Is it saying the nil pointer is a field on the MagickWand or on your own Image?

**Comment by loehnertz** [comment]
No problem, here is the stacktrace:
```
http: panic serving: runtime error: invalid memory address or nil pointer dereference

net/http.(*conn).serve.func1(0xc4200b0b40)
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1726 +0xd0
panic(0x42b6d60, 0x449acb0)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
gopkg.in/gographics/imagick.v2/imagick.(*MagickWand).AdaptiveResizeImage(0x0, 0x3e8, 0x3e8, 0x0, 0xc42013e3f0)
	/Users/jloehnertz/gocode/src/gopkg.in/gographics/imagick.v2/imagick/magick_wand_image.go:60 +0x22
github.com/loehnertz/showcased/vendor/app/controller/mockups.renderMockups(0xc420061c60, 0xc420061c48, 0xc4200a67d0)
	/Users/jloehnertz/gocode/src/github.com/loehnertz/showcased/vendor/app/controller/mockups/mockups.go:58 +0xeb
github.com/loehnertz/showcased/vendor/app/controller/mockups.arrangeMockups(0xc420061c60, 0xc420061c48, 0xc420061c78)
	/Users/jloehnertz/gocode/src/github.com/loehnertz/showcased/vendor/app/controller/mockups/mockups.go:51 +0x68
github.com/loehnertz/showcased/vendor/app/controller/mockups.HandleMockupsRequest(0x43496e0, 0xc420150000, 0xc42014e000)
	/Users/jloehnertz/gocode/src/github.com/loehnertz/showcased/vendor/app/controller/mockups/mockups.go:31 +0x13e
github.com/loehnertz/showcased/vendor/app/route.routeUpload(0x43496e0, 0xc420150000, 0xc42014e000)
	/Users/jloehnertz/gocode/src/github.com/loehnertz/showcased/vendor/app/route/routes.go:22 +0x9a
net/http.HandlerFunc.ServeHTTP(0x4323d18, 0x43496e0, 0xc420150000, 0xc42014e000)
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0x44a65a0, 0x43496e0, 0xc420150000, 0xc42014e000)
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc420099040, 0x43496e0, 0xc420150000, 0xc42014e000)
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4200b0b40, 0x4349b20, 0xc42009e440)
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2795 +0x27b
```

As I see it, the error occurs on `imagick.(*MagickWand).AdaptiveResizeImage()`.
I might be mistaken of course!

Can you retrieve any other useful information from the stacktrace regarding my issue? :)

**Comment by justinfx** [comment]
This function is concerning:
https://github.com/loehnertz/showcased/blob/master/vendor/app/controller/mockups/mockups.go#L40

It is called by an http handler, and it is initialising and destroying ImageMagick on every call. Don't do this. Call the initialize once for the entire application and the destroy once when you web server returns (or not at all). Otherwise you will have requests fighting each other to set up ImageMagick. 
Be careful with your use of defer. Obviously that is going to run when the function is over.

**Comment by loehnertz** [comment]
Oh dang!

That's a real oversight by me. You're totally right, I moved it to a better place, that is only run once.

The error still occurs though 😕 
That was a good fix apart from it, regardless!

**Comment by justinfx** [comment]
Hmm, ok. Shame that didn't fix it since it is always a common cause for these types of issues. Are you able to reduce the problem into a simple reproduction that I could test? If it isn't inherently broken from a standalone call to `AdaptiveResizeImage`, then it is probably a combination of your particular use case.

**Comment by loehnertz** [comment]
I tested a coupled of hours now, trying to rebuild a test setup for you!

With doing that I could pin down the issue to my function `createMagickWandInstances()` (https://github.com/loehnertz/showcased/blob/master/vendor/app/controller/mockups/mockups.go#L68).

It seems that the pointer doesn't resolve correctly. If I do this:
```go
func createMagickWandInstances(images *[]model.Image) {
	for i, image := range *images {
		image.AttachMagickWandInstance()
		(*images)[i] = image
	}
}
```
it works just fine and `AdaptiveResizeImage()` runs without any problem.

Is there a general error with the way I am handling a pointer to a slice of structs (`*[]model.Image`)?
Do have any other general hints on how to achieve what I am trying to do, which is running the method `image.AttachMagickWandInstance()` n-times for each item in the slice. Is there a better, more best-practise way that you are aware of?

Thanks a lot for your help, I still don't know if this error is expected with the way I did it or if for example the garbage collector kills the reference because of this pointer loop. 

If you got any hints, I'd be happy 😊

**Comment by justinfx** [comment]
Yep that would be the cause. Because you are storing value types `model.Image` in your slice, you get a copy each time you loop over them. When you attach the MagickWand, it is to a copy, leaving the values in your slice nil.

Both here, and in general, I would recommend ditching the pointer to a slice. This is only necessary if the function needs to append more modify the underlying array for the caller. But in your case you only operate on the existing elements:

```go
func createMagickWandInstances(images []model.Image) {
	for i, image := range images {
		image.AttachMagickWandInstance()
		images[i] = image
	}
}
```

I would even go a step further and deal only in `*model.Image`. This means you don't have to save the new copy back to the slice:

```
func createMagickWandInstances(images []*model.Image) {
	for _, image := range images {
		image.AttachMagickWandInstance()
	}
}
```

So it looks like this is just a Go issue and not imagick. Happy to close?

**Comment by justinfx** [comment]
No worries. It's hard to know whether it's a bug in imagick or not, when you are getting started and have a complex use case.
