### ISSUE TITLE
Suggestion - use runtime.SetFinalizer

### ISSUE THREAD

**Issue by x1unix** [gographics/imagick#244]
> Since this is a CGO binding, and the Go GC does not manage memory allocated by the C API, it is then necessary to use the Terminate() and Destroy() methods.

Recommend to take a look at [`runtime.SetFinalizer`](https://pkg.go.dev/runtime#SetFinalizer) method. Some other projects that have CGO bindings, use it for memory management ([example from gotk3](https://github.com/gotk3/gotk3/blob/master/gtk/application.go#L164))

**Comment by justinfx** [comment]
Hi. Have you looked at the codebase? We use finalizers extensively:
https://github.com/gographics/imagick/search?q=SetFinalizer&unscoped_q=SetFinalizer

Maybe the README was slightly confusing where it talks about destroying objects so ensure they are cleaned up much faster instead of relying on the GC to run the finalizer at some undefined later point in time (if at all)?

**Comment by x1unix** [comment]
@justinfx excuse me :)
