### ISSUE TITLE
PDF to jpeg gibberish

### ISSUE THREAD

**Issue by yangxh0306** [gographics/imagick#257]
For help, I am using is gopkg in/gographics/imagick v2/imagick, found the PDF files into jpeg files, jpeg file content garbled

Environmental centos7

**Comment by yangxh0306** [comment]
[ab12c31865a06f2320bf27f0aad94bd3.pdf](https://github.com/gographics/imagick/files/6846859/ab12c31865a06f2320bf27f0aad94bd3.pdf)

**Comment by justinfx** [comment]
Please post your example code to reproduce the problem. Also an example of the bad jpeg would help.
It could either be something in your code, or something wrong with your ImageMagick plugins.

**Comment by yangxh0306** [comment]
package main

import ("fmt"
	"gopkg.in/gographics/imagick.v2/imagick")

func ConvertPdfToJpg(srcImage, dstImage string, quality uint) {
	//Setup
	imagick.Initialize()
	defer imagick.Terminate()
	var err error
	mw := imagick.NewMagickWand()
	defer mw.Destroy()
	if err := mw.SetResolution(150, 150); err != nil {
		fmt.Printf("%v", err)
	}
	err = mw.ReadImage(srcImage)
	if err != nil {
		fmt.Printf("%v", err)
	}

	// Must be *after* ReadImageFile
	//// Flatten image and remove alpha channel, to prevent alpha turning black in jpg
	if err := mw.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_REMOVE); err != nil {
		fmt.Printf("%v", err)
	}

	if err := mw.SetImageCompression(imagick.COMPRESSION_JPEG); err != nil {
		fmt.Printf("%v", err)
	}


	// Set any compression (100 = max quality)
	if err := mw.SetCompressionQuality(quality); err != nil {
		fmt.Printf("%v", err)
	}

	// Select only first page of pdf
	mw.SetIteratorIndex(0)

	// Convert into JPG
	if err := mw.SetImageFormat("jpg"); err != nil {
		fmt.Printf("%v", err)
	}

	//导出图片
	_ = mw.WriteImage(dstImage)
}

func main() {
	ConvertPdfToJpg("/Users/Desktop/test.pdf", "/Users/Desktop/test.jpeg", 80)
}
[test.pdf](https://github.com/gographics/imagick/files/6852149/test.pdf)
![test](https://user-images.githubusercontent.com/74902299/126416106-960c7ff6-0bf2-4d6e-af66-68ee4e1643d4.jpeg)

**Comment by justinfx** [comment]
I've just tested your code, with your pdf, against ImageMagick-6.9.3, and the output jpeg looked fine. That makes me think something is wrong with either your pdf delegate (postscript) or your jpeg delegate (libjpeg). Have you tried to convert to another format such as tiff or png? What happens if you use the ImageMagick `convert` tool?

Also side question, are you using this code in production or is it just an example? I was concerned that you were Initializing and Terminating the ImageMagick support in each image conversion instead of once for the whole app.

**Comment by yangxh0306** [comment]
Thank you for your reply, I tried to use the ImageMagick convert tool and converted to PNG format, but after the transformation, the content of the title or the code, you try the transformed jpeg file is normal, can show?

**Comment by justinfx** [comment]
I don't really know what you are reporting. Please answer these questions clearly:

1. Did you try, in code, to convert from pdf to something other than jpg, such as png, and did it work correctly?
2. Did you try, using the `convert` commandline tool, to convert from pdf to jpeg?

I think you are asking if I tested the conversion using your code and would I post the resulting jpeg? Yes, I tested your exact code example, and the resulting jpeg looks exactly like your input pdf except a bit more blurry because of the 150/150 resolution setting.

**Comment by yangxh0306** [comment]
I'm sorry, may be I didn't describe clearly
1, I have been trying to convert PDF in your code to PNG, can transform, but the transformed results still do not match the PDF
2, I have been trying to use the convert command line tools to convert PDF to jpeg, but results still do not match the PDF after conversion


I hope you can upload your there after the conversion of jpeg files, in order to compare on my side.Thank you very much for your help

**Comment by justinfx** [comment]
If you have the **same** problem when using code **and** using the `convert` command **and** regardless of whether the output file is jpg or png, then your problem is with your ImageMagick installation or the ghostscript support for PDF files. There is not a problem with this projects Go language bindings to ImageMagick.

On my internal work machine it worked straight away using an ImageMagick6 that I built from source.

On my personal laptop I installed ImageMagick6 from apt, and the default configuration prevented PDF files from being used. So I had to edit my `/etc/ImageMagick-6/policy.xml` to disable the following line:

```
  <!-- <policy domain="coder" rights="none" pattern="PDF" /> -->
```

Here is an example of the output jpeg file that I created with your example code
![test](https://user-images.githubusercontent.com/282566/126691456-5a0425ef-9b8a-4239-822f-4f12de6f0c6c.jpeg)

**Comment by yangxh0306** [comment]
May be ghostscript support for PDF files, because from your output kpeg sample point of view, and my side is the same, the content of the jpeg title is garbled, not and original PDF is consistent, I'll try another solution.Thank you very much for your help.

**Comment by justinfx** [comment]
Good luck!
