### ISSUE TITLE
some pdf file Readblob very slow 

### ISSUE THREAD

**Issue by ben-swit** [gographics/imagick#270]
current i use imagick v3 in my project 

but when i call ReadImageBlob method then wait 7 sec 

here my code 

```go

//go:embed sample.pdf 
var file []byte

mw := imagick.NewMagickWand()
defer mw.Destroy()

start := time.Now()
if err := mw.ReadImageBlob(file); err != nil {
	return  err
}
end := time.Now().Sub(start)
```

result 

7sec 120ms 

i don't know how to perfomance upgrade 
if i have any solution? 

test pdf file size is  2mb
[sample.pdf](https://github.com/gographics/imagick/files/8078475/sample.pdf)

**Comment by justinfx** [comment]
ReadImageBlob just passes a pointer to the byte array into the C ImageMagick API. Not much else happens in the Go layer.
Is it slow if you use ReadImage or ReadImageFile?

**Comment by ben-swit** [comment]
@justinfx  unfortunately in project only use bytes  from web server io.reader

i'd test another size (3mb) pdf file but that file faster then sample.pdf    2sec 560ms

is there any possible causes?

**Comment by justinfx** [comment]
Well in the past I have seen users submit issues where certain pdf files are causing issues. I realise that your own app wants to use bytes blobs, but I was suggesting that for debugging purposes you save the bytes to a file and try a different api call. That will help isolate if it's a problem with the reading of blobs alone, or if it's just reading that pdf in any case.
You may want to look into your version of ghostscript as the plugin delegate doing the pdf handling for ImageMagick. It goes a bit beyond this binding library unfortunately. That is my guess.

**Comment by ben-swit** [comment]
@justinfx  I tried use ReadImage and ReadImageFile 
but use same time  
and time check  identify sample.pdf then 3.65s 

i think  some pdf file have overhead use cgo  

thanks for your comments

**Comment by justinfx** [comment]
I don't really know why cgo would make it slower depending on the pdf. Like I said, the only thing happening in Go is that a pointer to the bytes is passed to C ImageMagick. I don't think there is anything specific with the pdf happening in Go. 
Since you have confirmed that it happens in all cases with this given pdf, can you confirm if the command-line tool `convert` exhibits the same problem? That is an entirely standalone ImageMagick C tool hopefully build with the same ImageMagick and ghostscript delegate that your Go bindings are using.
