### ISSUE TITLE
[doubt] Why should not I mix the object creation methods?

### ISSUE THREAD

**Issue by mahesh-riddles** [gographics/imagick#296]
`mw1 := imagick.MagickWand{...}
    defer mw1.Destroy()

    mw2 := imagick.NewMagickWand()`

Why is it important not to mix object creation?
What is the issue if I do this?

**Comment by justinfx** [comment]
Really I think the README should be updated to say that you should always use the `New*` constructors and not use struct literals like `MagickWand{...}`. When you use struct literals, the counter is not incremented. But `Destroy()` always decrements the counter. So it ends up being incorrect when the `Terminate()` checks to see if everything has been destroyed.
Basically it doesn't make sense to mix the two approaches because the `New*` is the only way that properly tracks what has been created vs cleaned up.
Ultimately, it doesn't seem like it would cause a real problem in your application, if you don't care what happens at the point after you are calling `Terminate`, which is usually when the application is shutting down anyways. It just may not clean up certain ImageMagick C resources properly.

**Comment by justinfx** [comment]
Do you think the README should be updated to make it more clear, or are you happy with the explanation?

**Comment by mahesh-riddles** [comment]
I am happy with the explanation. I understood now. Thanks for that.
