### ISSUE TITLE
Random SIGSEGV: segmentation violation panics on Linux

### ISSUE THREAD

**Issue by BrandSnob** [gographics/imagick#299]
Hello, I have made several functions that edit images, like creating text, bluring and such.
I have been noticing these random crashes on Github's Actions that i have on my repo (private repo).
They were rare, but still.
Anyway, I used to run the app on server (Docker, Alpine image) and the app crashing on random functions that work with images and imagick.
All of them are `SIGSEGV: segmentation violation`. and as far as I see, all of them crash with these last logs:
```
 /__t/go/1.21.4/x64/src/runtime/cgocall.go:157 +0x4b fp=0xc000e4cf78 sp=0xc000e4cf40 pc=0x41814b
gopkg.in/gographics/imagick.v3/imagick._Cfunc_MagickGetImageBlob(0x7effaf2e2810, 0xc000848a10)
_cgo_gotypes.go:5014 +0x4c fp=0xc000e4cfa0 sp=0xc000e4cf78 pc=0x250816c
gopkg.in/gographics/imagick.v3/imagick.(*MagickWand).GetImageBlob.func1(0x5a?, 0x1?)
```
I'm not sure why that happen, could it be because of memory or CPU limits?
the server has 2.5GB RAM and 2 vCPU. CPU usage without image works is at about 4% and memory at about 35%.

I have used `imagick.Initialize()` and `defer imagick.Terminate()` carefully, at the start of `cmd/main.go` main function. even used a time.sleep between initialize and tests but the crash still happen.

**Comment by justinfx** [comment]
GetImageBlob, I think, is going to end up going through delegate plugins, depending on your output format. It could be related to those libraries as well.
If you search the history of issues on this project you will find that the Alpine image is not a reliable choice because it uses a different libc with the musl compiler and you have to make sure everything is compiled properly. Have you been able to reproduce this issue with a non-alpine image, using glibc?

**Comment by justinfx** [comment]
Nice. I'm glad that was an easy fix.
I think if you do it the right way and compile all of the components with musl, it could be possible to use alpine. It's just thay ImageMagick uses a lot of 3rf party libraries as delegate plugins.
I can add a note to the readme suggesting that using an alpine image is got advanced users that know how to set it up and support potential crashes.

**Comment by van-eth** [comment]
> Nice. I'm glad that was an easy fix. I think if you do it the right way and compile all of the components with musl, it could be possible to use alpine. It's just that ImageMagick uses a lot of 3rd party libraries as delegate plugins. I can add a note to the readme suggesting that using an alpine image is for advanced users who know how to set it up and support potential crashes.

Confirming, managed to get it finally working,  just build it instead of install from apt repository.

Your Dockerfile can start from:
```
ARG GOLANG_VERSION=1.22.0-alpine3.19
FROM golang:${GOLANG_VERSION} AS base
WORKDIR /src
RUN apk update && apk add build-base wget
RUN wget https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.1-29.tar.gz
RUN tar xvf 7.1.1-29.tar.gz
WORKDIR ImageMagick-7.1.1-29
RUN ./configure && make -j$(nproc)
RUN make install
RUN ldconfig /usr/local/lib
...
```

P.S. Also noticed bad performance on Mac m1 imagemagick stable 7.1.1-29 (brew). In my case speed inside ARM Debian/Alpine container is ~70x faster (700ms vs 10ms).
