### ISSUE TITLE
2.6.4 regression trouble GetImageBlob()/GetImagesBlob()

### ISSUE THREAD

**Issue by tophe** [gographics/imagick#319]
hi,

bumping 2.6.3 to 2.6.4 I find a regression bug in mw.GetImageBlob() && mw.GetImagesBlob().
In the joined code which compare GetImageBlob with WriteImate(), you see that in 2.6.4 it produce an empty image with GetImageBlob() and a correct image with WriteImage(), in 2.6.3 you have the 2 images that are correct. 
I have extract that from my running code to help find where is the problem and it appear only if you call mw.QueryFontMetrics(dw, text) before calling GetImageBlob(), it return null.
you can try with by commenting //fm := mw.QueryFontMetrics(dw, text)
[imtest.zip](https://github.com/gographics/imagick/files/15481934/imtest.zip)

I am using IMAGEMAGICK_VERSION=6.9.13-11, and golang v1.22.3.

**Comment by justinfx** [comment]
The change in 2.6.4 was to check for an error from the C function call before deciding to return the bytes. In your test code, can you try checking `mw.GetLastError()` if the GetImageBlob returns nil?

**Comment by justinfx** [comment]
Also, if what you are finding is that GetLastError is actually an error from your font query call, and it is being returned as well after the blob call, then maybe there is a bug where we need to clear the errors at the start of the blob calls.

**Comment by tophe** [comment]
hi justin,

I try to test mw.GetLastError() with:
`
	fm := mw.QueryFontMetrics(dw, text)
	fmt.Printf("%v\n", mw.GetLastError())
	sx := fm.TextWidth
	sy := fm.TextHeight
	fmt.Printf("%v,%v\n", sx, sy)

	data := mw.GetImageBlob()
	if data == nil {
		fmt.Printf("%v\n", mw.GetLastError())
	}
`
then it is <nil> in the 2 calls.

**Comment by justinfx** [comment]
Did you get an error?

**Comment by tophe** [comment]
sorry, no error.
you can try it, it is included in the joined zip file.

**Comment by justinfx** [comment]
Yea I'm able to repro it now. The error is actually:
```
WARNING_TYPE: unable to read font `FreeSansBold' @ warning/annotate.c/RenderType/964
```
But the implementation of `GetLastError` is clearing it after it is checked by `GetImageBlob` so that you cant check it yourself after. I will figure out a solution

**Comment by tophe** [comment]
It's because you don't have the font on your computer, but in my case I have it, and it just work with the 2.6.3 but not with 2.6.4.

I join a zip file containing my docker env, so you just add it in the imtest code and run :
`
docker build -t imtest .
docker run --rm --name imtest -ti -v.:/app imtest bash
`
then in the container you can try the example with

`
go run example.go
`


[Dockerfile.zip](https://github.com/user-attachments/files/15514848/Dockerfile.zip)

**Comment by justinfx** [comment]
Thanks for the Dockerfile. It's actually the same error using your docker image as well:

```
WARNING_TYPE: unable to read font `FreeSansBold' @ warning/annotate.c/RenderType/1001
```

Do you want to try it as well? You can replicate it by cloning the imagick [319_GetImageBlob](https://github.com/gographics/imagick/tree/319_GetImageBlob) branch to a local location and pointing a work file at it from your imtest module:

```
go work init
go work use <path/to/imagick/root>
```

There is a debug print line in `GetImageBlob` that will print the error before it is cleared.

What this means to me is that we check for an error in `GetImageBlob` and see this one from the `C.MagickGetImagesBlob` call, and then just return `nil`. But because the call to `GetLastError` also clears the error, you cannot then check it yourself in your code. I have a couple options for how to fix this.

1. I can update `GetImageBlob` to use a form of checking the error that won't clear it, so we know to return `nil` and then the caller still needs to cal `GetLastError` to check. We can update the docstring to suggest this.
2. I can break the function signature in a minor release, that instead does `func (mw *MagickWand) GetImageBlob() ([]byte, err)` so that we directly return the error
3. I can add another variant of the method, `GetImageBlobErr` that returns `([]byte, err)`

**Comment by justinfx** [comment]
FWIW, I think I want to go with option 1. It won't break existing code and it is quite easy to check for `nil` and then check the error if you want.

**Comment by tophe** [comment]
Option 1  doesn't break existing code that's cool ! updating the gostring for the call to GetLastError is the easier way.
But the option 2 is more go idiomatic, and so easier access for go coder ! 
Perhaps a small breaking change should be a lot better for the long  term support.
also, the method GetImagesBlob have the same concern.

in 2.6.3 that was working without errors, I just learn the font wasn't found in the container!

**Comment by justinfx** [comment]
Went with the breaking API change and a new minor release:
https://github.com/gographics/imagick/releases/tag/v2.7.0

**Comment by tophe** [comment]
hi justin, 

thank you for your support.
