### ISSUE TITLE
Vulnerability to "Biggest image in the smallest space"

### ISSUE THREAD

**Issue by maticmeznar** [gographics/imagick#49]
You may have heard about the recent "attack" on image processing libraries and systems using them:
https://www.bamsoftware.com/hacks/deflate.html 
https://news.ycombinator.com/item?id=10158529

I'm just wondering, if I'm using gographics/imagick package, how can I defend against this kind of attacks? How can I set resource limits? Looking at the docs, I've found ResourceType type, but I don't know how to use that to set the limits as I'm just learning Go. I'm using this library to resize and recompress user submitted images.

**Comment by justinfx** [comment]
Hi, 

This is an interesting read and I have to admit I am not quite experienced with the problem. It isn't  very specific to these Go bindings or Go at all, since this library is a *very thin* wrapper around the ImageMagick C api. Ultimately the best answer might come from the ImageMagick community forums. 

But looking at ResourceType, unfortunately it is woefully under-documented in ImageMagick (if we could even call it documented at all). And the C source code surrounding setting the resourced doesn't have comments. Searching google, however, suggests that some of these values are expressed in megabytes. But even that is shakey info. 
I believe what you want is RESOURCE_MEMORY,  with a limit in megabytes. This is supposed to produce a failure (fatal crash? error?) when ram consumption for a wand exceeds the limit. RESOURCE_DISK may be the size of the disk pixel cache, and RESOURCE_FILE may either refer to max write file size or max file read size. 

Also, I don't know why we have SetResourceLimit() exposed as a method of a wand. It is actually a regular function that doesn't apply to different wands. It should really be a regular function.
