### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by Ivanezko** [gographics/imagick#64]
golang app that resizes images
works fine with alone requests
but if i try to make several resizes quickly - got this:

fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x7f276656096e pc=0x7f276656096e]

runtime stack:
runtime.throw(0x9d3f80, 0x2a)
        /usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 19 [syscall, locked to thread]:
runtime.cgocall(0x7acee0, 0xc820044980, 0x0)
        /usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc820044950 sp=0xc820044920
github.com/gographics/imagick/imagick._Cfunc_MagickReadImage(0x7f2760025a40, 0x7f2760027a90, 0x7f2700000000)
        ??:0 +0x35 fp=0xc820044980 sp=0xc820044950
github.com/gographics/imagick/imagick.(*MagickWand).ReadImage(0xc82014e020, 0xc820136177, 0x59, 0x0, 0x0)
        /go/src/github.com/gographics/imagick/imagick/magick_wand_image.go:2165 +0x82 fp=0xc8200449b8 sp=0xc820044980
app/cropper.CropImage(0x7f2766e95bb0, 0xc8201442c0, 0xc82015a0e0)
        /go/src/app/cropper/cropper.go:78 +0x7f9 fp=0xc820044b78 sp=0xc8200449b8
net/http.HandlerFunc.ServeHTTP(0xa0f958, 0x7f2766e95bb0, 0xc8201442c0, 0xc82015a0e0)
        /usr/local/go/src/net/http/server.go:1422 +0x3a fp=0xc820044b98 sp=0xc820044b78
net/http.(*ServeMux).ServeHTTP(0xc82006f050, 0x7f2766e95bb0, 0xc8201442c0, 0xc82015a0e0)
        /usr/local/go/src/net/http/server.go:1699 +0x17d fp=0xc820044bf0 sp=0xc820044b98
net/http.serverHandler.ServeHTTP(0xc820012480, 0x7f2766e95bb0, 0xc8201442c0, 0xc82015a0e0)
        /usr/local/go/src/net/http/server.go:1862 +0x19e fp=0xc820044c50 sp=0xc820044bf0
net/http.(*conn).serve(0xc820144210)
        /usr/local/go/src/net/http/server.go:1361 +0xbee fp=0xc820044fa8 sp=0xc820044c50
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc820044fb0 sp=0xc820044fa8
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1910 +0x3f6

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f2766e95910, 0x72, 0xc82000a180)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82006ca70, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82006ca70, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82006ca10, 0x0, 0x7f2766e95a08, 0xc820142240)
        /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820038098, 0x465f30, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820038098, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc820012480, 0x7f2766e959d0, 0xc820038098, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc820012480, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc82000bb00, 0x5, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1967 +0x8f
main.main()
        /go/src/app/main.go:50 +0x62f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

**Comment by justinfx** [comment]
Can you show an example of your code and how you are using imagick? 

I have used imagick within an http service and performed many resizes, quickly. Are you trying to share an instance of a MagickWand across goroutines? Are you trying to initialize and terminate the Imagick environment from multiple goroutines. 

Make sure you create and destroy unique MagickWand instanced in each http request

**Comment by Ivanezko** [comment]
http.HandleFunc("/crop", cropper.CropImage)
http.ListenAndServe(server, nil)
package cropper


import (
   "github.com/gographics/imagick/imagick"
   "log"
   "net/http"
   "strconv"
   "fmt"
   "time"
)


func init() {

}

// Resize image
func CropImage(w http.ResponseWriter, r *http.Request) {
....


   imagick.Initialize()
   defer imagick.Terminate()

   mw := imagick.NewMagickWand()
   defer mw.Destroy()

   start := time.Now()
   err = mw.ReadImage(fileName)
   if err != nil {
      panic(err)
   }
   log.Printf("Loading image took %v\n", time.Now().Sub(start))
   start = time.Now()
   err = mw.CropImage(uint(source_width), uint(source_height), int(source_x), int(source_y))
   if err != nil {
      panic(err)
   }
   log.Printf("Cropping image took %v\n", time.Now().Sub(start))
   start = time.Now()
   err = mw.ResizeImage(uint(width), uint(height), imagick.FILTER_LANCZOS, 1)
   if err != nil {
      panic(err)
   }
   log.Printf("Resizing image took %v\n", time.Now().Sub(start))
   start = time.Now()
   err = mw.SetImageCompressionQuality(95)
   if err != nil {
      panic(err)
   }

   err = mw.SetImageFormat("JPEG")
   if err != nil {
      panic(err)
   }

   blob := mw.GetImageBlob()

   w.Header().Set("Content-type", "image/jpeg")
   w.Header().Set("X-Accel-Expires", "604800")

   fmt.Fprintf(w, "%s", blob)

   log.Printf("Printing image took %v\n", time.Now().Sub(start))

}

**Comment by justinfx** [comment]
```
func CropImage(w http.ResponseWriter, r *http.Request) {
...
   imagick.Initialize()
   defer imagick.Terminate()
```

Don't do that. You are supposed to do it once for the entire application. You are tearing down the entire ImageMagick system after each request :-)

You can move this to your application main(), or an init function. If you put it in an init() function, you should only need the initialize() call. A webserver probably doesnt need to call terminate()

**Comment by Ivanezko** [comment]
thank you very much!
you saved my day

**Comment by justinfx** [comment]
No problem!

**Comment by fvm** [comment]
I'm experiencing this exact same issue. Moreover, I've verified that I only initialise imagick just once, in the init, so that doesn't appear to be the cause.

Below you can find the (start of) stacktrace of one of the panics, specifically, the part which I keep seeing with every panic, i.e. from "ReadImage` onwards.

As with the original case, this doesn't occur upon processing occasional individual images, but when we start processing images quickly it does.

```
[signal 0xb code=0x1 addr=0x40 pc=0x7f35815e4890]
runtime stack:
runtime.throw(0xac3660, 0x2a)
/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
goroutine 9229 [syscall, locked to thread]:
runtime.cgocall(0x8429e0, 0xc82013cda0, 0xc800000000)
/usr/local/go/src/runtime/cgocall.go:123 +0x11b fp=0xc82013cd50 sp=0xc82013cd20
stash.tools.bol.com/mir/escher/vendor/gopkg.in/gographics/imagick.v2/imagick._Cfunc_MagickReadImageBlob(0x7f35980012a0, 0xc820754000, 0x1f4646, 0x0)
??:0 +0x41 fp=0xc82013cda0 sp=0xc82013cd50
stash.tools.bol.com/mir/escher/vendor/gopkg.in/gographics/imagick.v2/imagick.(*MagickWand).ReadImageBlob(0xc820222660, 0xc820754000, 0x1f4646, 0x1f4646, 0x0, 0x0)
```

Now, one of the things I do is use a Sync.Pool, like below. Perhaps these somehow conflict?
```
var wandPool = sync.Pool{
	New: func() interface{} {
		m := imagick.NewMagickWand()
		return m
	},
}
```

**Comment by justinfx** [comment]
To be honest, I am not really sure what happens when you use cgo resources in a `sync.Pool`. I tried to find some information on it, but didn't come up with much more than someone saying "we were using cgo resources in a sync.Pool and it didn't play nice". I do know that `sync.Pool` clears the objects during each garbage collection, so the advantage would be to reuse allocation between each garbage collection.

Did profiling show that creating new wands each time and freeing them was a bottleneck? If so, maybe you should try a standard free list cache instead of sync.Pool and see if that fixes your issue. 

Also, do you have an example of how you are reusing the wand from the pool? What operations do you call on the reused wand each time? Are you retaining any objects that were created from the wand, beyond the point when you put the wand back in the pool?

In my own experience using Imagick within a web-based image server, my implementation used a pool of workers to do image processing. Each worker would create and destroy wands each time, but I would only have, say 4 workers (or something matching the available cpus). I never used a free list or pool for the wands because I just figured creating a new wand is significantly less time than it takes to process images with it.

**Comment by fvm** [comment]
I implemented this thinking any re-use of the wand would be preferable over recreating and destroying one every time. I use a `[]byte` represented as a type `Image` internally to store the blob and move the blob to and from the wand at the beginning and end (through `defer`) of every processing step, making sure to call `func (mw *MagickWand) Clear()`:
```
// Get a wand and give it the data
func (i *Image) toWand() (w *imagick.MagickWand, err error) {
	w = wandPool.Get().(*imagick.MagickWand)

	w.Clear()

	err = w.ReadImageBlob(i.blob)
	if err != nil {
		logrus.Errorf("Error while reading blob to wand: %s", err)
		return
	}
	w.ResetIterator()

	return
}

// Retrieve the data from the wand and put it back
func (i *Image) doneWithMagickWand(w *imagick.MagickWand) {
	w.ResetIterator()
	i.blob = w.GetImagesBlob()
	w.Clear()
	wandPool.Put(w)
	return
}
```

Now, I've changed the `Sync.Pool` out for a straighforward `NewMagickwand()` and, importantly, a `Destroy()` and it does seem that letting the garbage collector sweep the pool without the wand being explictly destroyed was the cause of the unexpected signal. I've been throwing a few hundred images at it and no problems at all.

So, yeah, the idea of using `Sync.Pool` seemed attractive, if only to gain a tiny bit of performance increase (as in my case milliseconds count), but causes more problems than it's worth as it skips the `Destroy()` part of the cycle.

**Comment by justinfx** [comment]
Did profiling actually show a performance advantage to the sync pool? 

Actually as of #80 (v2.2.0) MagickWand, along with other related types, had a finalizer added so that they would auto destroy when garbage collected. So calling Destroy manually only kills the C object sooner rather than later. Are you using >= 2.2.0 already? 

Something must be getting reused after destruction with that sync Pool set up. Like I said, if profiling shows that you are wasting significant time creating and destroying wants compared to manipulating your images, you could see if a channel-based free list or similar would help. At least it's more predictable with the management of the objects since they never destroy. 

I was wondering... If you were to reuse a single wand the way you do, in just a single goroutine looping 100s of times reading and clearing, do you see the problem?

**Comment by fvm** [comment]
As to the bottleneck, no there was no real bottleneck, but any increase of performance, in this case by using the `Sync.Pool`, seemed desirable. As that only seems to obfuscate matters in this case, I just removed it and resorted to just calling `NewMagickWand()` and `Destroy()`.

Now, the troubling thing is that it did *seem* to fix the issue, it now turns out that, although decreased in frequency, the panic does still occur sometimes. So even without the pool, it still occurs.

The revision I'm using is f45c5377a5c0fcad01a9f754dfd7108f788dbc84 (v2.2.2). For completeness, here's the code which creates and clears wands and loads the image bytes to the wand:
```
package renderer

import (

	"github.com/Sirupsen/logrus"

	"gopkg.in/gographics/imagick.v2/imagick"
)

func init() {
	imagick.Initialize()
}

type Image struct {
	blob []byte
}

// Get a wand and give it the data
func (i *Image) toWand() (w *imagick.MagickWand, err error) {
	w = imagick.NewMagickWand()

	w.Clear()

	err = w.ReadImageBlob(i.blob)
	if err != nil {
		logrus.Errorf("Error while reading blob to wand: %s", err)
		return
	}
	w.ResetIterator()

	return
}

// Retrieve the data from the wand and destroy it
func (i *Image) doneWithMagickWand(w *imagick.MagickWand) {
	w.ResetIterator()
	i.blob = w.GetImagesBlob()
	w.Clear()
	w.Destroy()
	return
}
```

And here's an example of how I call it:
```

type jpeg struct {
	Image
}

// ... [SNIP] ...

func (j *jpeg) Trim(opt RenderOptions) error {
	defer toc(tic(), "Trim")

	if opt.Trimfactor <= 0 {
		logrus.Debugf("Skipping trim, trimfactor set to: %v", opt.Trimfactor)
		return nil
	}

	logrus.Debugf("Trimming image with a factor of %v", opt.Trimfactor)

	wand, err := j.toWand()
	defer j.doneWithMagickWand(wand)
	if err != nil {
		logrus.Error(err)
		return err
	}

	err = wand.TrimImage(float64(opt.Trimfactor))
	if err != nil {
		logrus.Errorf("Error during image trimming: %v", err)
		return err
	}

	return nil
}
```

**Comment by justinfx** [comment]
I guess I would need to create a runnable reproduction of this problem. I'm not sure why the wand is bad when you go to read a blob with it.

**Comment by rogierlommers** [comment]
What can we do to figure out the reason the wand is bad at the moment? And by the way, @justinfx , thanks for your help!!

**Comment by rogierlommers** [comment]
Some additional info: in our (I'm a colleague of @fvm ) case we indeed initiate imagick only once and every magic wand is being `destroyed` after use. This works for the cases that incoming bytes are jpg and we use imagick to create a jpg as well. When the incoming bytes are a pdf, then we still get the error.

Any additional suggestions? For example how to debug this?

**Comment by rogierlommers** [comment]
Well, the story continues. We can almost pinpoint it to Docker who f$cks up. When I run inside docker container --> panics, when I run on node itself (NOT in container) --> everything is smooth.

More info to come this Monday.

**Comment by justinfx** [comment]
@rogierlommers , that's interesting. Please keep me informed. Before you pointed out docker, I was going to suggest that it might have to do with the pdf delegate. That is, the libraries installed to satisfy pdf support. Because if it works great with JPG but then crashes within pdf, that would probably indicate it is somewhere in the plugin interactions. 
Have you been able to run it from a debugger to catch the crash and inspect the C stack?

**Comment by justinfx** [comment]
Copying my reply from #96 as it might be helpful... 

Re:
http://imagemagick.org/discourse-server/viewtopic.php?t=23365

Apparently you can set MAGICK_DEBUG to trace and see debug output from ImageMagick. I wonder if it is hanging like in that link or if it's looping on something in the C library

**Comment by fvm** [comment]
Cheers Justin, I was already considering compiling debug versions and what have you... I'll look into it

**Comment by justinfx** [comment]
That link seemed to indicate that it was only a runtime environment logging flag. I haven't tried it yet. But that would definitely be easier than needing to compile with debug.

**Comment by rogierlommers** [comment]
Here is a repo which pinpoints the problem: https://github.com/rogierlommers/go-panics

**Comment by justinfx** [comment]
Thanks for putting together the reproduction. I will try to find time to have a look at it.

**Comment by rogierlommers** [comment]
> Thanks for putting together the reproduction. I will try to find time to have a look at it.

Sorry, please don't put effort in yet. Still not 100% able to reproduce.

**Comment by rogierlommers** [comment]
Also I think it is related to this: https://github.com/gographics/imagick/issues/96
