### ISSUE TITLE
couldn't build the library on ubuntu 12.04 with go1.5.2.linux-386

### ISSUE THREAD

**Issue by palaiyacw** [gographics/imagick#68]
For more details kindly look into this SO link 

http://stackoverflow.com/questions/34764612/unable-to-build-magick-for-golang

**Comment by justinfx** [comment]
Hi,

What version of ImageMagick is installed? `convert -version`

If you installed it via `apt-get`, then you shouldn't need to be using the `no_pkgconfig` build tag. That is used when you have ImageMagick installed in a custom location that is not known to `pkgconfig`, and you need to set the custom `CGO_` env vars to tell the build system how to find it.

So that being said, we should work forward with the standard build process.

**Comment by justinfx** [comment]
I've figured out what the problem is. It seems that those alpha channel type constants have changed over time in the ImageMagick source. Strangely, `FlattenAlphaChannel` was added on [Jan 27, 2012](http://git.imagemagick.org/repos/ImageMagick/commit/e39ed0bb9bf07c361de6992cd4df8999e3500ac4#5808302b4fff601e7513f797d3c3326976335c37_42_42) and then renamed to `RemoveAlphaChannel` on [Jan 30, 2012](http://git.imagemagick.org/repos/ImageMagick/commit/6180838cb97473afec7c383da0a4df02f2a29f40)

Can you give the `68_fix_AlphaChannelOptions` branch a try? I've aligned those constants with what looks like the ImageMagick 6.8.8-10 release. It's pretty confusing because the ImageMagick source repo doesn't appear to have any release tags so you just have to kind of line up the dates to the changelog. Also, these constants seem to change a bit over time, even beyond 6.8.9, so I don't think I can even make the `im-6.8.9` branch line up completely unless I just update it to the current state of `image.h`

Anyways, if that test branch works for you, I can merge it into `master`

**Comment by palaiyacw** [comment]
I noticed you have made changes in the alpha_channel_type.go file and I tried to build again with the 68_fix_AlphaChannelOptions branch. But again it gave me the error  
`# imagick
could not determine kind of name for C.RemoveAlphaChannel`

**Comment by justinfx** [comment]
Ok that's a 5 year old version of ImageMagick which is even older than the tested version listed in the README of this project. 

http://www.imagemagick.org/script/changelog.php

And it's an older version of Ubuntu thatbisbolder than the current stable release. 

I am not sure we are trying to make the master branch of imagick support every version of ImageMagick since the beginning. We have to draw a line somewhere. I may not even merge this test branch, because again it is for an older ImageMagick than we list in our README. I would be taking away supported features. 

Here is what I may do. I could remove this other constant and then leave it as a 6.6.x branch.Or you could just install a newer release of ImageMagick and not have these problems?

**Comment by palaiyacw** [comment]
I think the problem is not with the older version. I have build the latest version of ImageMagick 6.9.3-1 on ubuntu 12.04. Even though i am not able to build the library. Here is the snapshot of the screen 
![errorsnapshot](https://cloud.githubusercontent.com/assets/10070831/12384559/7ea7b406-bdd9-11e5-8d2b-7bf9c8ebedd9.PNG)

**Comment by justinfx** [comment]
Sorry about not replying sooner. I've been moving house and not had the ability to get back to testing this again. Hopefully I can look at it at some point this week. Strange that I have been able to build against 6.9.x without issues up to this point, which was how I was testing the im-6.8.9 branch previously

**Comment by palaiyacw** [comment]
would you mind checking it again?

**Comment by justinfx** [comment]
I looked at this again today. In both the `ImageMagick-6` head branch of the ImageMagick repo, as well as checking out commit 68758f76 which is their 6.9.3-1 release commit, I see both of those constants available in the header.

I was able to build the Imagick `im-6.8.9` branch against both of these checkouts from ImageMagick. This makes me think that you are maybe picking up older headers during build time. Can you try and report the results of the following...

Find out where your headers are (the path after the `-I`)`
```
pkg-config --cflags MagickWand
```

See if those constants are actually defined:

```
grep -r Flatten /path/to/ImageMagick/includes/magick/image.h
```

Also, try building Imagick with the verbose flags to confirm which ImageMagick locations are being picked up:

```
go build -x -v github.com/gographics/imagick/imagick
```

You should end up seeing `-I<path/to/ImageMagick/includes>` somewhere in the output. What we are interested in, is seeing which `magick/image.h` you are ending up with, and what constants are really defined.

**Comment by palaiyacw** [comment]
Thanks a lot @justinfx for your time and effor. Even though after installing the latest version i didn't change the ImageMagick.pc file from /usr/lib/pkgconfig folder. So, it was reading the wrong values of CGO_CFLAGS and CGO_LDFLAGS.

**Comment by justinfx** [comment]
Awesome. Thanks for confirming that the im-6.8.9 branch works for you. I may still update the constants for the Master branch, to be 6.8.8-10 compatible

**Comment by jackluo2012** [comment]
apt-get update && \
    apt-get install -qy \
        pkg-config \
        imagemagick \
        libmagickwand-dev \
        libmagickcore-dev \
====-------------
# ActivitApi/vendor/gopkg.in/gographics/imagick.v3/imagick
../vendor/gopkg.in/gographics/imagick.v3/imagick/affine_matrix.go:8:35: fatal error: MagickWand/MagickWand.h: No such file or directory
 #include <MagickWand/MagickWand.h>
                                   ^
compilation terminated.
root@0ba7ccd9d595:/go/src/ActivitApi# pkg-config --cflags MagickWand
-fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6
root@0ba7ccd9d595:/go/src/ActivitApi# grep -r Flatten /usr/include/ImageMagick-6/
magick/ wand/

**Comment by jackluo2012** [comment]
`FROM golang:latest
MAINTAINER  jackluo
# Ignore APT warnings about not having a TTY
ENV DEBIAN_FRONTEND noninteractive

# install build essentials
RUN apt-get update && apt-get install -y wget build-essential pkg-config --no-install-recommends && \
# install imagemagick 6.9.1-7
 cd && \
    wget http://www.imagemagick.org/download/ImageMagick-7.0.7-11.tar.gz && \
    tar xvzf ImageMagick-7.0.7-11.tar.gz && \
    cd ImageMagick-* && \
    ./configure && \
    make && make install && \
    ldconfig /usr/local/lib && \
    rm -rf ImageMagick-7.0.7-11 && \
    rm -rf ImageMagick-7.0.7-11.tar.gz && \
    #clear up
    apt-get remove -y wget && \
    apt-get autoremove -y && \
    apt-get autoclean && \
    apt-get clean
`
