### ISSUE TITLE
How to import to Docker?

### ISSUE THREAD

**Issue by wigywizzle** [gographics/imagick#91]
I've been trying for a few days now to import this to Docker using the official goLang dockerfile, but have been unsuccessful.  Since this package isn't popular, running apt-get won't work.  I've (hesitantly) tried to just add the files to the container, but that didn't work.  Here's the DockerFile I've built and the error it produces:
===DOCKERFILE===

    # 1) Use the official go docker image built on debian.
    FROM golang:latest
    
    # 2) ENV VARS
    ENV GOPATH $HOME/<PROJECT>
    ENV PATH $HOME/<PROJECT>/bin:$PATH
    
    # 3) Grab the source code and add it to the workspace.
    ADD . /<GO>/src/<PROJECT>
    ADD . /<GO>/gopkg.in
    # Trying to add the files manually... Doesn't help.
    ADD . /opt/local/share/doc/ImageMagick-6
    
    
    # 4) Install revel and the revel CLI.
    #(The commented out code is from previous attempts)
    #RUN pkg-config --cflags --libs MagickWand
    #RUN go get gopkg.in/gographics/imagick.v2/imagick
    RUN go get github.com/revel/revel
    RUN go get github.com/revel/cmd/revel
    
    # 5) Does not work... Can't find the package.
    #RUN apt-get install libmagickwand-dev
    
    # 6) Get godeps from main repo
    RUN go get github.com/tools/godep
    
    # 7) Restore godep dependencies
    WORKDIR /<GO>/src/<PROJECT>
    RUN godep restore
    
    # 8) Install Imagick
    #RUN go build -tags no_pkgconfig gopkg.in/gographics/imagick.v2/imagick
    
    # 9) Use the revel CLI to start up our application.
    ENTRYPOINT revel run <PROJECT> dev 9000
    
    # 10) Open up the port where the app is running.
    EXPOSE 9000

===END DOCKERFILE===

This allows me to build the docker container, but when I try to run it, I get the following error in the logs of kinematic:

===DOCKER ERROR===

    ERROR 2016/08/20 21:15:10 build.go:108: # pkg-config --cflags MagickWand MagickCore MagickWand MagickCore
    pkg-config: exec: "pkg-config": executable file not found in $PATH
    2016-08-20T21:15:10.081426584Z 
    ERROR 2016/08/20 21:15:10 build.go:308: Failed to parse build errors:
     #pkg-config --cflags MagickWand MagickCore MagickWand MagickCore
    pkg-config: exec: "pkg-config": executable file not found in $PATH
    2016-08-20T21:15:10.082140143Z 

===END DOCKER ERROR===

**Comment by justinfx** [comment]
Hi. Most of the information about this ticket is not really specific to iMagick support. It is really just a general question for something like the golang-nuts list or a docker community. But I can spot a few issues in your process..

```
#RUN go build -tags no_pkgconfig gopkg.in/gographics/imagick.v2/imagick
```

You are using the `go build` command instead of the `go install` command. `build` is only something you would use for executables since it does not install anything and just produces a binary. But libraries don't produce executable, so, nothing happens.

Also in the attempts you are using that don't use the `-tags no_pkgconfig`, you clearly don't have the `pkg-config` tool available in your Docker image. 

```
#RUN pkg-config --cflags --libs MagickWand
```

This does nothing. It would just print things to your terminal about the location of the includes and libs for the installed ImageMagick. Try it in your own linux shell.

There are two ways you can approach putting this into a Docker image. Either you want to bring an existing ImageMagick from your host into your container (which you have an example of) or you want to load it from within the Docker file (the other example you are doing via apt-get).

If you bring it into your Docker image by adding it from the host, then you will have to set the CGO_CFLAGS/CGO_LDFLAGS env flags and use `-tags no_pkgconfig`, as described in the readme. This tells the build to find the libs in a custom location. 

If you use apt-get to install ImageMagick, I would think you would then just use the standard build process with no `-tags`, and let `pkg-config` find the libs for you. This implies that your Docker image has the `pkg-config` tool.

Hope this helps. Nothing much else than this is iMagick specific.

**Comment by wigywizzle** [comment]
This helps a lot.  Thanks for taking the time to do such a thorough explanation.  I still don't have it 100% working, but I'm definitely back on track.

**Comment by justinfx** [comment]
Hey no worries. Hope you get it figured out. Happy to help I'd there are issues specific to imagick
